### PR TITLE
Swap our old CoC for the CNCF CoC,

### PR DESCRIPTION
**Pull request by jberkus**
as requested by the TOC.

This merge must be endorsed by a majority of the KubeVirt Maintainers, since it changes our code of conduct.

Attn: @fabiand @rthallisey @vladikr @rmohr @stu-gott @vasiliy-ul @mazzystr @fgimenez

### CODE REVIEW

**Comment by cwilkers** [comment]
/lgtm
I like the more concise and specific wording of the CNCF version in terms of applying policy, though the old version was more conversational.

**Review by davidvossel — COMMENTED** [review]
/lgtm

**Comment by rmohr** [comment]
looks like we need two more. @fabiand @rthallisey @vasiliy-ul

**Comment by jberkus** [comment]
OK, looks like there's enough votes ... @rmohr can you merge it?

**Pull request merged**
