### PR TITLE
Document workflow

### PR DESCRIPTION
**Pull request by iranzo**
Document article workflow and troubleshooting  local vs CI/CD

FIle at: https://github.com/kubevirt/community/blob/f19cc78a7775e5086ebbe6ad84b4fdeac74fd4ff/docs/article-workflow.md

### CODE REVIEW

**Comment by codificat** [comment]
One thing that needs to change in the PR: it touches 28 files and does quite a few more things than what it describes it does.

It's supposed to add one new file with content, right? Then please move any other changes to a separate PR and document these accordingly.

**Comment by iranzo** [comment]
> One thing that needs to change in the PR: it touches 28 files and does quite a few more things than what it describes it does.
> 
> It's supposed to add one new file with content, right? Then please move any other changes to a separate PR and document these accordingly.

Rebased on top of https://github.com/kubevirt/community/pull/45

**Comment by ptrnull** [comment]
After review the content it looks good to me.
/lgtm
@codificat I let it up to you to approve.

**Comment by mazzystr** [comment]
/lgtm
/approve

Thanks for this.  I've been running yasspeller manually!

**Comment by codificat** [comment]
@mazzystr I believe this will need some updates after your work on kubevirt/kubevirt.github.io#636 and related work, but it's time to
/approve
this version

**Pull request merged**
