### PR TITLE
Update membership-policy to specify valid OWNERS files in sponsor requirements

### PR DESCRIPTION
**Pull request by alromeros**
Hello everyone,

This PR aims to introduce a small update in the membership policy so the requirements for sponsors are better explained.

Best regards.

### CODE REVIEW

**Review by jean-edouard — COMMENTED** [review]
So if you're a reviewer/approver in any `github.com/kubevirt/` repo you can be a sponsor on all the repos? That seems a bit too permissive to me...
I think it would make more sense for reviewers/approver of a given repo to be allowed to sponsor others only on that same repo.
What do you think?

**Comment by alromeros** [comment]
Hi @jean-edouard! I agree that it may be a little too permissive, however, I understand that those sponsors are just for allowing joining the organization as a member, which is unrelated to individual repositories. Correct me If I'm wrong, but in that case, I think It wouldn't make that sense to limit sponsorships to be on the same repo.

**Review by jean-edouard — COMMENTED** [review]
@alromeros my bad, I wrongly assumed we were in the `reviewers` section.
/approve

**Comment by cwilkers** [comment]
Thanks, this is a good clarification of the policy

/approve
/lgtm

**Pull request merged**
