### PR TITLE
owners: adding myself as an approver

### PR DESCRIPTION
**Pull request by jean-edouard**
**What this PR does / why we need it**:
I've been a reviewer for a few years now, and this repository lacks active approvers, so this is my nomination.
/cc @aburdenthehand @AlonaKaplan @cwilkers @davidvossel @fabiand @rmohr @vladikr

### CODE REVIEW

**Comment by dhiller** [comment]
@fabiand @davidvossel any objections? Or can we get this one in?

**Comment by aburdenthehand** [comment]
/lgtm
And an emphatic one at that. Thanks for stepping up, jed :D

**Comment by rmohr** [comment]
/lgtm

well deserved

**Comment by iholder101** [comment]
I definitely think @jean-edouard is a great fit.
/lgtm

Saying that, I think we still need a more general solution to the lack of approvers in this repo (like suggested in [here](https://github.com/kubevirt/community/pull/297)).

**Comment by aburdenthehand** [comment]
/approve

And +1 to @iholder101's comment

**Pull request merged**
