### PR TITLE
sig-compute: Introduce instancetype sub project

### PR DESCRIPTION
**Pull request by lyarwood**
**What this PR does / why we need it**:

This PR breaks the instance type feature out into a sub project [1] within the compute SIG.

The aim being to delegate ownership to individuals working in this area in an effort to help drive the API and overall feature towards v1 and GA. 

As sub projects have yet to be fully utilised within KubeVirt this PR also serves as a way to test out their use within the project given recent attempts to redefine and introduce working groups etc.

[1] https://github.com/kubernetes/community/blob/master/governance.md#subprojects

**Which issue(s) this PR fixes** *(optional, in `fixes #<issue number>(, fixes #<issue_number>, ...)` format, will close the issue(s) when PR gets merged)*:
Fixes #

**Special notes for your reviewer**:

The associated OWNER_ALIASES changes are provided by https://github.com/kubevirt/kubevirt/pull/12062 that will need to land first ahead of this change for the paths listed under `owners` to be valid.

**Checklist**

This checklist is not enforcing, but it's a reminder of items that could be relevant to every PR.
Approvers are expected to review this list.

- [ ] Design: A [design document](https://github.com/kubevirt/community/tree/main/design-proposals) was considered and is present (link) or not required
- [ ] PR: The PR description is expressive enough and will help future contributors
- [ ] Code: [Write code that humans can understand](https://en.wikiquote.org/wiki/Martin_Fowler#code-for-humans) and [Keep it simple](https://en.wikipedia.org/wiki/KISS_principle)
- [ ] Refactor: You have [left the code cleaner than you found it (Boy Scout Rule)](https://learning.oreilly.com/library/view/97-things-every/9780596809515/ch08.html)
- [ ] Upgrade: Impact of this change on upgrade flows was considered and addressed if required
- [ ] Testing: New code requires [new unit tests](https://github.com/kubevirt/kubevirt/blob/main/docs/reviewer-guide.md#when-is-a-pr-good-enough). New features and bug fixes require at least on e2e test
- [ ] Documentation: A [user-guide update](https://github.com/kubevirt/user-guide/) was considered and is present (link) or not required. You want a user-guide update if it's a user facing feature / API change.
- [ ] Community: Announcement to [kubevirt-dev](https://groups.google.com/g/kubevirt-dev/) was considered

**Release note**:

```release-note
NONE
```

### CODE REVIEW

**Comment by lyarwood** [comment]
/cc @iholder101 
/cc @jean-edouard 

As the current chairs for sig-compute would you mind taking a look at this draft suggestion to break the instance type feature out into a sub project within the compute SIG. This is an alternative to another SIG (as discussed in https://github.com/kubevirt/community/pull/299) or WG (I believe discussed privately downstream?).

https://github.com/kubevirt/kubevirt/pull/12062 provides the OWNER_ALIASES changes within kubevirt itself.

**Comment by lyarwood** [comment]
> Seems fair to me. @fabiand what do you think?

https://github.com/kubevirt/kubevirt/pull/12062#issuecomment-2162355024

@xpivarc when you have time I'd also appreciate your thoughts on this before we move forward.

**Review by xpivarc — APPROVED** [review]

**Comment by xpivarc** [comment]
/cc @fabiand @enp0s3 @stu-gott @aburdenthehand  ...
Please have a look

**Review by aburdenthehand — COMMENTED** [review]
/lgtm
Yep, makes sense to me.

**Review by enp0s3 — APPROVED** [review]
Looks good to me

**Comment by vladikr** [comment]
Looks good to me as well. Thanks @lyarwood.
/approve

**Pull request merged**
