### PR TITLE
Propose molecule-kubevirt presentation

### PR DESCRIPTION
**Pull request by jseguillon**
Hi, 
I'm working on a Kubevirt driver for Ansible Molecule and I propose to explain and demo it. 

Please find details in markdown. 

Regards.

### CODE REVIEW

**Comment by codificat** [comment]
Thank you for submitting this session proposal for the KubeVirt summit!

We are working to prepare a schedule that can accommodate as many of the received proposals as possible, according to and capacity available in the event.

We might have to request some adjustments to some of the proposals in order to achieve that goal.

More feedback will be provided next week.

Looking forward to meeting you at the event!

**Comment by jseguillon** [comment]
For your information : I wrote a small Medium post to explain why this driver and how to use : https://joel-seguillon.medium.com/molecule-kubevirt-driver-bf2e462629ed

**Review by davidvossel — APPROVED** [review]
Due to receiving more content than the event has capacity for, we had to quickly form a review team (thanks Red Hat and NVIDIA) to make difficult decisions about what presentations to accept.

**This session has been accepted!**

We ask that presentation slides be submitted by Friday, Feb 5th 2021. 

More information pertaining to the event schedule, event platform, and how to submit slides will be made available to you soon. If at any point you find that you are unable to present, please let us know as soon as possible so we can fill your slot from our wait list. 

Thank you for your submission and support of the KubeVirt Community.

**Comment by jseguillon** [comment]
Hi @davidvossel thanks for the acceptance 👍 

Could you please tell me if there's a required Theme and/or Tool for the slides ? If not required : any preferred ?

**Comment by davidvossel** [comment]
> Could you please tell me if there's a required Theme and/or Tool for the slides ? If not required : any preferred ?

@jseguillon My only recommendation at the moment is that slides are formatted for wide screens and that you use a tool that is capable of exporting the slides to PDF for upload.

**Comment by jseguillon** [comment]
Hi @davidvossel 
I just realized the event is in PST time zone. Since I'll be streaming from France (UTC+1), I'd really appreciate if you could schedule my session before PST  3pm (midnight in France). This would avoid me looking too tired ^^ 

Anyway if not possible dont' worry, I'll adapt !

**Comment by codificat** [comment]
Just to clarify: the event schedule is 14:00 – 19:00 UTC, i.e. 15:00–20:00 in France (and 06:00–11:00 PST).

**Comment by jseguillon** [comment]
Oh ok 😬 Thanks a lot for this information!

**Comment by jseguillon** [comment]
Hi @davidvossel ,
I sent draft presentation link for Google Slides to your Red Hat email address.

**Pull request merged**
