### PR TITLE
Fix link in membership_policy.md

### PR DESCRIPTION
**Pull request by dominikholler**
Signed-off-by: Dominik Holler <dholler@redhat.com>

### CODE REVIEW

**Review by dhiller — APPROVED** [review]
Looks good to me!

@mazzystr I think we need to do something in order to have more people that can review PRs in this repo, I've seen that @codificat is still in the OWNERS file...

**Review by jean-edouard — APPROVED** [review]

**Comment by cwilkers** [comment]
Fixes #118 Thanks!

/approve

**Pull request merged**
