### PR TITLE
sigs, labels: add observability label

### PR DESCRIPTION
**Pull request by dhiller**
**What this PR does / why we need it**:
Adds the sig label to the yaml section of the SIG observability.

**Which issue(s) this PR fixes** *(optional, in `fixes #<issue number>(, fixes #<issue_number>, ...)` format, will close the issue(s) when PR gets merged)*:
Fixes #

**Special notes for your reviewer**:
/cc @jcanocan @machadovilaca

### CODE REVIEW

**Comment by jcanocan** [comment]
Thanks for taking care of these matters.
Looks good to me. However, I'm not directly involved in observability topics.

**Comment by dhiller** [comment]
@aburdenthehand tiny change, I've added the label on the sigs.yaml for observability, since I always tend to forget which one is correct - would you be able to take a quick look at this?

**Comment by aburdenthehand** [comment]
/approve
Thanks @dhiller

**Comment by dhiller** [comment]
> /approve

@machadovilaca could I ask for an lgtm from you, please?

**Pull request merged**
