### PR TITLE
sigs: Nominate Edward Haas (eddev) as the sig-network chair

### PR DESCRIPTION
**Pull request by EdDev**
Edward is currently acting as the sig-network approver on the kubevirt/kubevirt project.

**Which issue(s) this PR fixes** *(optional, in `fixes #<issue number>(, fixes #<issue_number>, ...)` format, will close the issue(s) when PR gets merged)*:
Fixes #

**Special notes for your reviewer**:

**Checklist**

This checklist is not enforcing, but it's a reminder of items that could be relevant to every PR.
Approvers are expected to review this list.

- [ ] Design: A [design document](https://github.com/kubevirt/community/tree/main/design-proposals) was considered and is present (link) or not required
- [ ] PR: The PR description is expressive enough and will help future contributors
- [ ] Code: [Write code that humans can understand](https://en.wikiquote.org/wiki/Martin_Fowler#code-for-humans) and [Keep it simple](https://en.wikipedia.org/wiki/KISS_principle)
- [ ] Refactor: You have [left the code cleaner than you found it (Boy Scout Rule)](https://learning.oreilly.com/library/view/97-things-every/9780596809515/ch08.html)
- [ ] Upgrade: Impact of this change on upgrade flows was considered and addressed if required
- [ ] Testing: New code requires [new unit tests](https://github.com/kubevirt/kubevirt/blob/main/docs/reviewer-guide.md#when-is-a-pr-good-enough). New features and bug fixes require at least on e2e test
- [ ] Documentation: A [user-guide update](https://github.com/kubevirt/user-guide/) was considered and is present (link) or not required. You want a user-guide update if it's a user facing feature / API change.
- [ ] Community: Announcement to [kubevirt-dev](https://groups.google.com/g/kubevirt-dev/) was considered

**Release note**:
```release-note
NONE
```

### CODE REVIEW

**Comment by vladikr** [comment]
/approve

I thought you are already ;)

**Review by jean-edouard — APPROVED** [review]

**Comment by jean-edouard** [comment]
@EdDev looks like you need to run `make generate`

**Review by dhiller — COMMENTED** [review]
/lgtm

Thank you @EdDev for stepping into this role and making SIG Network more approachable - also for owning the work that this likely will add up to the things you do already :mountain: 

One note - you should find someone else who will take the second chair role, i.e. for the likes of taking well-deserved holiday.

(not necessarily in this PR though)

**Comment by dhiller** [comment]
> /lgtm
> 
> Thank you @EdDev for stepping into this role and making SIG Network more approachable - also for owning the work that this likely will add up to the things you do already ⛰️
> 
> One note - you should find someone else who will take the second chair role, i.e. for the likes of taking well-deserved holiday.
> 
> (not necessarily in this PR though)

One other thing - self nominating yourself to a chair position is fine for now, however we should think about how we are doing this in the future - I think you @EdDev  already issued a concern here. 

FYI @aburdenthehand

**Comment by EdDev** [comment]
> One note - you should find someone else who will take the second chair role, i.e. for the likes of taking well-deserved holiday.

Agreed. We are working towards finding and preparing a member for the role, but it will take time.

> One other thing - self nominating yourself to a chair position is fine for now, however we should think about how we are doing this in the future - I think you @EdDev already issued a concern here.

Yes, this is not that nice.
I guess this should be done by either an existing chair or by an organization lead or committee. I am not sure if we established such a thing yet. I just know @vladikr is a de-facto such lead at the moment.

**Pull request merged**
