### PR TITLE
community, owners: add aburdenthehand as approver

### PR DESCRIPTION
**Pull request by dhiller**
I think the community manager should be part of the approvers list.

/cc @fabiand @davidvossel @vladikr

### CODE REVIEW

**Comment by dhiller** [comment]
@cwilkers would you have time to take a quick look?

**Comment by aburdenthehand** [comment]
@dhiller Thanks! I'm happy to be a reviewer as well. 
Also as Chandler pointed out on another PR, I technically already have these permissions through the [orgs.yaml](https://github.com/kubevirt/project-infra/blob/main/github/ci/prow-deploy/kustom/base/configs/current/orgs/orgs.yaml#L937) as part of the community team, but it would be good to have this owners file reflect that - and also so I can be assigned as reviewer for prs :)

**Comment by dhiller** [comment]
> @dhiller Thanks! I'm happy to be a reviewer as well. Also as Chandler pointed out on another PR, I technically already have these permissions through the [orgs.yaml](https://github.com/kubevirt/project-infra/blob/main/github/ci/prow-deploy/kustom/base/configs/current/orgs/orgs.yaml#L937) as part of the community team, but it would be good to have this owners file reflect that - and also so I can be assigned as reviewer for prs :)

Yes, exactly: It's one way to have all the rights to merge PRs via access, it's another way to have the `OWNERS` file communicate this. And that was my intent. But fair point of putting you into reviewers list also.

**Review by brianmcarey — COMMENTED** [review]
/lgtm

**Pull request merged**
