### PR TITLE
sigs,generate: improve validation, update sig-list generation

### LINKED ISSUE #321: sig-list.md: create postsubmit prow job that updates after changes to sigs.yaml
**Is your feature request related to a problem? Please describe**:
Currently, whenever [sigs.yaml] is updated, [sig-list.md] (which is generated from [sigs.yaml] needs to get updated by calling:

```bash
make generate
```

**Describe the solution you'd like**:
A way that tells the user that they need to update [sig-list.md] by running the above command before the merge is completed.

Easiest might be a presubmit job that calls the target and checks whether the git state is clean.

**Describe alternatives you've considered**:
Variants of that might be:
* a postsubmit that is executed after changes to [sigs.yaml] or
* a periodic 
either way they call the target and create a pull request afterwards.

**Additional context**:
* [example of an existing postsubmit for community sigs.yaml](https://github.com/kubevirt/project-infra/blob/main/github/ci/prow-deploy/files/jobs/kubevirt/community/community-postsubmits.yaml#L8)

/good-first-issue

[sigs.yaml]: https://github.com/kubevirt/community/tree/main/sigs.yaml
[sig-list.md]: https://github.com/kubevirt/community/blob/main/sig-list.md

### PR DESCRIPTION
**Pull request by dhiller**
**What this PR does / why we need it**:

This PR improves the validation of `sigs.yaml` - it checks entries with 
* existing directories (sig/wg)
* existing labels (using project-infra labels.yaml)
* whether github accounts are actually org members (using project-infra orgs.yaml)

If `--dry-run` flag is `false` it will overwrite the orgs.yaml with the result, where each entry that failed to check will have been removed.

Also it adds to make target `generate` the run of the validation with `--dry-run=false` which will lead to a modified sigs.yaml which in turn will update the sig-list.md with corrected entries, which will then fail the check whether all changes have been committed.

This effectively will automate the validation whether all changes are correct and have been applied to generated markdown.

**Which issue(s) this PR fixes** *(optional, in `fixes #<issue number>(, fixes #<issue_number>, ...)` format, will close the issue(s) when PR gets merged)*:
Fixes #321

**Special notes for your reviewer**:

### CODE REVIEW

**Comment by dhiller** [comment]
> @dhiller: The following test **failed**, say `/retest` to rerun all failed tests or `/retest-required` to rerun all mandatory failed tests:
> 
> Test name	Commit	Details	Required	Rerun command
> pull-community-make-generate	[a519c22](https://github.com/kubevirt/community/commit/a519c22e725f20081e2737ff170fbcc2fb380881)	[link](https://prow.ci.kubevirt.io/view/gs/kubevirt-prow/pr-logs/pull/kubevirt_community/350/pull-community-make-generate/1856357354740649984)	true	`/test pull-community-make-generate`

Error makes sense, since we need to modify the presubmit to add the project-infra directory, so that the binary can access it.

**Comment by dhiller** [comment]
/hold

since this PR requires an update of `pull-community-make-generate` - it needs the project-infra checkout to access `labels.yaml` and `orgs.yaml` as described in PR description.

**Comment by dhiller** [comment]
> pull-community-make-generate

Fixed by https://github.com/kubevirt/project-infra/pull/3761

**Comment by dhiller** [comment]
/unhold 

should be ready to go in now.

**Comment by dhiller** [comment]
/hold

to wait for https://github.com/kubevirt/project-infra/pull/3762 to go in

**Comment by dhiller** [comment]
https://github.com/kubevirt/project-infra/pull/3762 is required to go in before this can work - however we should make this land soon, since it ensures that no more errors wrt labels and github handles sneak in.

FYI @vladikr @aburdenthehand

**Comment by aburdenthehand** [comment]
/lgtm
On premise but I can't review the code

**Comment by dhiller** [comment]
As a followup we should remove the `pull-community-validate-sigs-yaml` job, since the call is added here anyway

**Comment by dhiller** [comment]
> As a followup we should remove the `pull-community-validate-sigs-yaml` job, since the call is added here anyway

https://github.com/kubevirt/project-infra/pull/3779 will remove the presubmit

**Comment by dhiller** [comment]
/uncc @cwilkers 
/cc @vladikr 

Adding Vladik for attention around sigs.yaml validation (hope you find the time :) )

**Comment by aburdenthehand** [comment]
/lgtm
Just re-adding the label from before :)

**Comment by dhiller** [comment]
> /lgtm Just re-adding the label from before :)

@aburdenthehand sorry, but could you do me the favor of taking a look again - had to rebase due to changes for observability.

**Review by EdDev — APPROVED** [review]
Looks great, thanks!

**Comment by dhiller** [comment]
/unhold

The PR should now really really really be ready to go in.

**Review by EdDev — APPROVED** [review]

**Comment by vladikr** [comment]
@dhiller Thanks for this PR! 
It looks good to me. I didn't find any major issues. 
/approve

**Pull request merged**
