### PR TITLE
Create contributing.md

### PR DESCRIPTION
**Pull request by mazzystr**
Stub page per ....
* [kubevirt/community#87](https://github.com/kubevirt/community/issues/87)
* And to resolve [user-guide/issues/341](https://github.com/kubevirt/user-guide/issues/341) otherwise make check_links will fail CI and block the pull_req that resolves that issue.

### CODE REVIEW

**Comment by mazzystr** [comment]
@davidvossel Hey can you review/approve/lgtm this really quick?

**Comment by stu-gott** [comment]
This is a placeholder then?

**Review by davidvossel — COMMENTED** [review]
/approve
/lgtm

sorry, i've very backlogged on my github mentions.

**Pull request merged**
