### PR TITLE
Adding responsibilities doc for SIG storage meeting

### PR DESCRIPTION
**Pull request by aburdenthehand**
Based off the existing community meeting and sig-scale docs

Signed-off-by: Andrew Burden <aburden@redhat.com>

### CODE REVIEW

**Review by jean-edouard — APPROVED** [review]

**Review by aglitke — APPROVED** [review]

**Comment by aburdenthehand** [comment]
@jobbler Are you able to approve this when you have a moment? Thank you!

**Comment by akalenyu** [comment]
There is a little more on the google doc than in here, but if that is fine then it's lgtm
https://docs.google.com/document/d/1mqJMjzT1biCpImEvi76DCMZxv-DwxGYLiPRLcR6CWpE/edit#

**Comment by aburdenthehand** [comment]
@akalenyu sorry, I missed your comment.
Yeah, that's intentional. This should really only need to capture the long-term, consistent details necessary for someone to join and find the minutes from previous meetings.

**Pull request merged**
